# This workflow will install Python dependencies, run tests, lint, and check formatting with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Linting and typing

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  linting-and-typing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.13.2
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"

      - name: Install dependencies
        working-directory: ./
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Typing with mypy
        run: |
          mypy --ignore-missing-imports --install-types --non-interactive .

      - name: Lint with Ruff
        working-directory: ./
        run: |
          ruff check --output-format=github --config ruff.toml .
